### ISSUE TITLE
please make available the rosbag you used in the benchmark

### ISSUE THREAD

**Issue by facontidavide** [CNR-STIIMA-IRAS/binary_logger#1]
I believe that the problem with the matlab import is not the rosbag, but the parser. to validate my hypothesis I would like to use the same file you used

**Comment by enricovillagrossi** [comment]
I have done the test using this parser https://github.com/bcharrow/matlab_rosbag. We have also tested the native rosbag package provided from MATLAB and the test took more than 10 minutes. 
The .bag file used for the test is 180MB. Can you provide me dropbox/Google Drive/wetransfer?

**Comment by facontidavide** [comment]
It make more sense if you share the file on YOUR dropbox/Google Drive.

Otherwise, use wetransfer to send the file davide.faconti@gmail.com

I worked on this package that can be used as a rosbag parser. https://github.com/facontidavide/ros_type_introspection

I have the feeling that my benchmark will be somehow in the between yours and the one of bcharrow.

**Comment by enricovillagrossi** [comment]
Ok, you are right it makes sense to use dropbox, here the link:
https://www.dropbox.com/sh/bhw9p4v1mtipghj/AACrKvH5wguug6dd-S7vGr6ba?dl=0

**Comment by facontidavide** [comment]
Thank you very much, interestingly my preliminary tests reveal that I can parse the file in [plotjuggler](https://github.com/facontidavide/PlotJuggler) in about 4.5 seconds. Roughly speaking this means that a rosbag to MATLAB importer would take about the same amount of time.

Consider that my parser can extract information from any ROS type, not only a set of known ones; extractions rules are created at runtime. So it can't really compete with your approach ;)

__IMPORTANT NOTE:__ If I compress your file with LZ4 (rosbag compress --lz4) the filesize is reduced to __32 MB__ and the deserialization takes exactly the same amount of time.

Feel free to close this ticket

**Comment by enricovillagrossi** [comment]
Yes, you are right your software is faster than the MATLAB rosbag parser.
**NOTE:** MATLAB rosbag parser can't work with the compressed bag file.

**Comment by facontidavide** [comment]
Are you sure? I am 99% sure that the ability to decompress a rosbag file is implicitly provided by __<rosbag/view.h>__

Anyway, this is not really my point. I am too busy developing [PlotJuggler](https://github.com/facontidavide/PlotJuggler) right now as an ALTERNATIVE to MATLAB for quick visualization, but in the future I might want to build a rosbag to MATLAB conversion plugin, as I mentioned.

Thanks again for sharing your work

**Comment by enricovillagrossi** [comment]
Thank you for your appreciation.
Just to clarify: 

using the MATLAB (r2015a) **native rosbag function**
**Code:**

`tic`
`bag = rosbag('fake_joint_state.bag');`
`js_bag = select(bag, 'Topic', '/fake_joints_state');`
`fprintf('create bag file=%f\n',toc)`
`tic`
`[ts,cols] = timeseries(js_bag);`
`fprintf('read bag file=%f\n',toc)`

**Error:**
Error using test_bag_speed (line 4)
The parser only supports uncompressed bagfiles. At least one chunk in the file is compressed. Try using the "rosbag decompress" utility in the standard ROS environment to decompress this bag file.


while the [matlab_rosbag](https://github.com/bcharrow/matlab_rosbag) works but the parsing time doesn't change.

**Comment by facontidavide** [comment]
I was wrong :)
